### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by shinnn**

### CODE REVIEW

**Comment by jo** [comment]
https://travis-ci.org/jo/http-image-size

**Comment by jo** [comment]
Would you like to add the badge?

**Comment by shinnn** [comment]
@jo I'll add it soon on master.

**Comment by jo** [comment]
Thanks!

**Comment by shinnn** [comment]
Done in 5353a54bd60c4890fe5470d44dae07bd7c843a4c

**Pull request merged**
